# Generated by Django 5.1.6 on 2025-03-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_educationexperience_jobexperience_projectexperience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationexperience',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='jobexperience',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='projectexperience',
            old_name='user',
            new_name='author',
        ),
    ]
