# Generated by Django 5.1.6 on 2025-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectexperience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='skills',
            field=models.ManyToManyField(related_name='education_experiences', to='api.skill'),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='skills',
            field=models.ManyToManyField(related_name='job_experiences', to='api.skill'),
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='skills',
            field=models.ManyToManyField(related_name='project_experiences', to='api.skill'),
        ),
    ]
