# Generated by Django 5.1.6 on 2025-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationexperience',
            name='major',
        ),
        migrations.RemoveField(
            model_name='educationexperience',
            name='title',
        ),
        migrations.RemoveField(
            model_name='jobexperience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projectexperience',
            name='article_link',
        ),
        migrations.RemoveField(
            model_name='projectexperience',
            name='project_link',
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='focus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='gpa_scale',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
