on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Django System Check
      run: python manage.py check


  deploy-backend:
    runs-on: ubuntu-latest
    needs: backend-checks
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy backend via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        run: |
          echo "Starting deployment to FastResume backend..."
          set -e
          cd ~/Git/fastresume/backend
          source venv/bin/activate

          echo "Pulling latest changes from main branch..."
          git pull origin main

          echo "Installing dependencies..."
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "Django collectstatic and migrate..."
          python manage.py collectstatic --noinput
          python manage.py migrate --noinput
          python manage.py check

          echo "Restarting FastResume backend..."
          if [ -f gunicorn.pid ]; then
            sudo kill -HUP $(cat gunicorn.pid) # restart Gunicorn
          else
            echo "No Gunicorn PID file found, restarting systemd service."
            sudo systemctl restart fastresumebackend # restart the service
          fi

          echo `date "+%Y-%m-%d %H:%M:%S.%3N"` ' FastResume updated' >> fastresumebackend_update.log
          echo "✅ FastResume updated and restarted successfully."
          